### ISSUE TITLE
Missing VirtualHotel.Data project in repo

### ISSUE THREAD

**Issue by kartalbas** [fscopel/AuthenticationAndAuthorization#1]
Hello Fabio, I was searching for an example application with JWT Token Authentication and Authorization written in net core 3.1. 

After cloning your repo, opening, I face an issue, that the VirtualHotel.Data project is missing in your repo. If there is no sensitiv data, would you also share this project?

thanks.
Mehmet

**Comment by fscopel** [comment]
@kartalbas thank you for pointing it out. Just committed the project.
